version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./Backend
    container_name: flask-backend
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    command: flask run --host=0.0.0.0 --port=5000
    volumes:
      - ./Backend:/app

volumes:
  mongo_data:
